### ISSUE TITLE
search_posts_by_hashtag raised JSONDecodeError

### ISSUE THREAD

**Issue by GreenLim** [sudoguy/tiktok_bot#9]
great work!
but i encountered the following problem:

2019-11-25 18:42:12.571 | INFO     | tiktok_bot.api.api:search_hashtags:219 - Search 1 hashtags with keyword: "cat"
Searching hashtags: 10it [00:01,  9.46it/s]                                                                                                           2019-11-25 18:42:13.632 | INFO     | tiktok_bot.api.api:search_hashtags:231 - Found 1 results
Searching hashtags: 10it [00:01,  9.46it/s]
2019-11-25 18:42:13.632 | INFO     | tiktok_bot.api.api:search_posts_by_hashtag:186 - Search 10 posts with hashtag: "cat"
Searching posts:   0%|                                                                                                         | 0/10 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "tiktok.py", line 14, in <module>
    posts = bot.search_posts_by_hashtag("cat", count=10)
  File "***path/.venv/lib/python3.7/site-packages/tiktok_bot/bot/bot.py", line 55, in search_posts_by_hashtag
    posts = self.api.search_posts_by_hashtag(hashtag=tags[0], count=count)
  File "***path/.venv/lib/python3.7/site-packages/tiktok_bot/api/api.py", line 191, in search_posts_by_hashtag
    response = self._search_posts_by_hashtag(search_request)
  File "***path/.venv/lib/python3.7/site-packages/tiktok_bot/api/api.py", line 177, in _search_posts_by_hashtag
    search = ListPostsInHashtagResponse(**response.json())
  File "***path/.venv/lib/python3.7/site-packages/httpx/models.py", line 930, in json
    return jsonlib.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

does search_posts_by_hashtag function need login?

**Comment by MaxiFilippov** [comment]
Did you solve it? I got the same error

**Comment by Muzammil099** [comment]
Not yet

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MaxiFilippov** [comment]
Actualle, response is empty

**Comment by adebayor123** [comment]
Any updates?
